version: "3.9"
services:
  air-quality:
    image: karopolopoulos/air-quality:latest
    build: .
    container_name: air-quality
    env_file: .env
    restart: always
    volumes:
      - "./certs:/air-quality/certs"
    devices:
      - "/dev/SDS011:/dev/SDS011"
