version: "3.9"
services:
  air-quality:
    image: karopolopoulos/air-quality:latest
    build: .
    container_name: air-quality
    env_file: .env
    volumes:
      - "./certs:/air-quality/certs"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
