service: air-quality

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2

resources:
  Resources:
    PiThing:
      Type: AWS::IoT::Thing
      Properties:
        ThingName: ${self:service}-${self:provider.stage}-raspberry-pi

    # PiCertificate:
    #   Type: AWS::IoT::Certificate
    #   Properties:
    #     CertificateSigningRequest: #certificate
    #     Status: ACTIVE

    PiPolicy:
      Type: AWS::IoT::Policy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - iot:*
              Resource: "*"

    PiPrincipleAttachment:
      Type: AWS::IoT::PolicyPrincipalAttachment
      Properties:
        PolicyName:
          Ref: PiPolicy
        Principal: arn:aws:iot:ap-southeast-2:085082512559:cert/cce29d782080cbaf2e0d0db5b6510dd71093536ad523e732be7ea422aaeb49be

    PiThingAttachment:
      Type: AWS::IoT::ThingPrincipalAttachment
      Properties:
        Principal: arn:aws:iot:ap-southeast-2:085082512559:cert/cce29d782080cbaf2e0d0db5b6510dd71093536ad523e732be7ea422aaeb49be
        ThingName:
          Ref: PiThing
  # look at greengrass
